import { ReactNode } from "react";
import Head from 'next/head'

type Props = {
    children?: ReactNode
}

const Layout = ({ children }: Props) => {
    return (
        <div>
            <Head>
                <title>Quickid</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {children}
            </main>
        </div>
    )
};

export default Layout;
